accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
]

cinema/urls.py
from django.contrib import admin
from django.urls import path, include

from cinema import settings
from ticketing import views

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('admin/', admin.site.urls),
    path('ticketing/', include('ticketing.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticketing/urls.py
from django.urls import path, register_converter
from django.urls.converters import BitYadConverter

from ticketing import views

register_converter(BitYadConverter, 'movie_id')

app_name = 'ticketing'
urlpatterns = [
    path('movie/list/', views.movie_list, name='movie_list'),
    path('movie/details/<movie_id:movie_id>/', views.movie_details, name='movie_details'),
    path('cinema/list/', views.cinema_list, name='cinema_list'),
    path('cinema/details/<int:cinema_id>/', views.cinema_details, name='cinema_details'),
    path('showtime/list/', views.showtime_list, name='showtime_list'),
    path('showtime/details/<int:showtime_id>/', views.showtime_details, name='showtime_details'),
    path('ticket/list/', views.ticket_list, name='ticket_list'),
    path('ticket/details/<int:ticket_id>/', views.ticket_details, name='ticket_details'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """
    Represent a user's profile
    """

    class Meta:
        verbose_name = 'نمایه کاربری'
        verbose_name_plural = 'نمایه کاربری'

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="حساب کاربری")
    # important fields stored in User model:
    #   first_name, last_name, email, date_joined

    phone_number = models.CharField(max_length=11, verbose_name='تلفن همراه')

    MALE = 1
    FEMALE = 2
    GENDER_CHOICES = (
        (MALE, 'مرد'),
        (FEMALE, 'زن'),
    )
    gender = models.IntegerField(choices=GENDER_CHOICES, verbose_name='جنسیت', null=True, blank=True)

    birth_date = models.DateField(verbose_name='تاریخ تولد', null=True, blank=True)
    address = models.TextField(verbose_name='آدرس', null=True, blank=True)
    profile_image = models.ImageField(verbose_name='تصویر', upload_to='users/profile_images/', null=True, blank=True)

    # field related to ticketing app
    balance = models.IntegerField(verbose_name='اعتبار', default=0)

    def __str__(self):
        return self.user.get_full_name()

    def get_balance_display(self):
        return '{} تومان'.format(self.balance)

    # behaviors
    def deposit(self, amount):
        self.balance += amount
        self.save()

    def spend(self, amount):
        if self.balance < amount:
            return False
        self.balance -= amount
        self.save()
        return True

accounts/views.py
from email.policy import HTTP

from django.contrib.auth import authenticate, login, user_logged_in, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


def login_view(request):
    # if user_logged_in:
    #     return HttpResponseRedirect(reverse('accounts:panel'))
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is None:
            context = {
                'username': username,
                'error': 'نام کاربری یا رمز عبور اشتباه است!',
            }
        else:
            login(request, user)
            return HttpResponseRedirect(reverse('accounts:profile'))
    elif request.user.is_authenticated:
        return HttpResponseRedirect(reverse('accounts:profile'))
    else:
        context = {}
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))


@login_required
def profile_view(request):
    profile = request.user.profile
    context = {
        'profile': profile,
    }
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/base_accounts.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>
        {% block page_title %}{% endblock %}
    </title>
    <!-- BS CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/main.css" %}">
</head>
<body>
    <div class="container">
        <div class="row my-2 py-2">
            <h1>
                سامانه فروش بلیت سینما
            </h1>
        </div>




    </div>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="{% static "ticketing/js/main.js" %}"></script>
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'ticketing/base_page.html' %}

{% block page_title %}
    ورود کاربران
{% endblock %}

{% block page_content %}
    <form action="" method="post" class="mx-auto my-5 p-3 bg-light">
        {% csrf_token %}
        <div class="row px-2">
            {% if error %}
                <div class="col alert alert-danger">
                    {{ error }}
                </div>
            {% endif %}
        </div>
        <div class="row p-3">
            <div class="col-auto">
                <input type="text" class="form-control" name="username" value="{{ username }}" placeholder="نام کاربری"
                       required>
            </div>
            <div class="col-auto">
                <input type="password" class="form-control" name="password" placeholder="رمز عبور" required>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary">ورود</button>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'ticketing/base_page.html' %}

accounts/templates/accounts/profile.html
{% extends 'ticketing/base_page.html' %}

{% block page_title %}
    پنل کاربری
{% endblock %}

{% block page_content %}
    <div class="col-2"></div>
    <div class="col-8 ">
        <div class="row my-5 p-4 bg-dark rounded">
            <div class="col-8 bg-light">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col" colspan="2" class="text-center">
                            به نمایه کاربری خودتون خوش آمدید
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">
                            نام و نام خانوادگی:
                        </th>
                        <td>{{ profile.user.get_full_name }}</td>
                    </tr><tr>
                        <th scope="row">
                            تلفن همراه:
                        </th>
                        <td>{{ profile.phone_number }}</td>
                    </tr>
                    <tr>
                        <th scope="row">
                            ایمیل:
                        </th>
                        <td>{{ profile.user.email }}</td>
                    </tr>
                    <tr>
                        <th scope="row">
                            جنسیت:
                        </th>
                        <td>{{ profile.get_gender_display }}</td>
                    </tr>
                    <tr>
                        <th scope="row">
                            تاریخ تولد:
                        </th>
                        <td>{{ profile.birth_date }}</td>
                    </tr>
                    <tr>
                        <th scope="row">
                            اعتبار:
                        </th>
                        <td>{{ profile.get_balance_display }}
                        <button type="button" class="btn btn-success">
                            افزایش اعتبار
                        </button></td>
                    </tr>
                    <tr>
                        <th scope="row">
                            آدرس:
                        </th>
                        <td>{{ profile.address }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-4 bg-light py-4 text-center">
                {% if profile.profile_image %}
                    <img style="width: 210px" src="{{ profile.profile_image.url }}"
                     alt="{{ profile.user.get_full_name }}"></td>
                {% else %}
                    <i class="fas fa-user fa-10x"></i>
                {% endif %}
                <div class="btn-group-vertical mt-4 btn-block" role="group" aria-label="Basic example">
                    <a role="button" class="btn btn-success" href="{% url "ticketing:ticket_list" %}">
                        بلیت های من
                    </a>
                    <button type="button" class="btn btn-warning">
                        تغییر نمایه
                    </button>
                    <button type="button" class="btn btn-info">
                        تغییر آدرس
                    </button>
                    <button type="button" class="btn btn-danger">
                        تغییر گذرواژه
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-2"></div>
{% endblock %}