accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
]

cinema/urls.py
from django.contrib import admin
from django.urls import path, include

from cinema import settings
from ticketing import views

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('admin/', admin.site.urls),
    path('ticketing/', include('ticketing.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticketing/urls.py
from django.urls import path, register_converter
from django.urls.converters import BitYadConverter

from ticketing import views

register_converter(BitYadConverter, 'movie_id')

app_name = 'ticketing'
urlpatterns = [
    path('movie/list/', views.movie_list, name='movie_list'),
    path('movie/details/<movie_id:movie_id>/', views.movie_details, name='movie_details'),
    path('cinema/list/', views.cinema_list, name='cinema_list'),
    path('cinema/details/<int:cinema_id>/', views.cinema_details, name='cinema_details'),
    path('showtime/list/', views.showtime_list, name='showtime_list'),
    path('showtime/details/<int:showtime_id>/', views.showtime_details, name='showtime_details'),
    path('ticket/list/', views.ticket_list, name='ticket_list'),
    path('ticket/details/<int:ticket_id>/', views.ticket_details, name='ticket_details'),
]

ticketing/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    """
    A Short Description about this Modeling
    """

    class Meta:
        verbose_name = 'فیلم'
        verbose_name_plural = 'فیلم'

    name = models.CharField(max_length=100, verbose_name='عنوان')
    director = models.CharField(max_length=50, verbose_name='کارگردان')
    year = models.IntegerField(verbose_name='سال تولید')
    length = models.IntegerField(verbose_name='مدت زمان')
    description = models.TextField(verbose_name='توضیحات')
    poster = models.ImageField('پوستر', upload_to='movie_poster/')

    def __str__(self):
        return self.name


class Cinema(models.Model):
    """
    A Short Description about this Modeling
    """

    class Meta:
        verbose_name = 'سینما'
        verbose_name_plural = 'سینما'

    cinema_code = models.IntegerField(primary_key=True, verbose_name='کد اختصاصی')
    name = models.CharField(max_length=50, verbose_name='نام')
    city = models.CharField(max_length=30, default='تهران', verbose_name='شهر')
    capacity = models.IntegerField(verbose_name='ظرفیت')
    phone_number = models.CharField(max_length=20, null=True, verbose_name='تلفن')
    address = models.TextField(verbose_name='آدرس')
    image = models.ImageField('تصویر', upload_to='cinema_images/', null=True, blank=True)

    def __str__(self):
        return self.name


class ShowTime(models.Model):
    """
    A Short Description about this Modeling
    """

    class Meta:
        verbose_name = 'سانس'
        verbose_name_plural = 'سانس'

    # choices between PROTECT, CASCADE, SET_NULL, SET_DEFAULT, SET(), DO_NOTHING
    movie = models.ForeignKey('Movie', on_delete=models.PROTECT, verbose_name='فیلم')
    cinema = models.ForeignKey('Cinema', on_delete=models.PROTECT, verbose_name='سینما')

    start_time = models.DateTimeField(verbose_name='زمان شروع')
    price = models.IntegerField(verbose_name='قیمت')
    salable_seats = models.IntegerField(verbose_name='صندلی های قابل فروش')
    free_seats = models.IntegerField(verbose_name='صندلی های آزاد')

    SALE_NOT_STARTED = 1
    SALE_OPEN = 2
    TICKETS_SOLD = 3
    SALE_CLOSED = 4
    MOVIE_PLAYED = 5
    SHOW_CANCELED = 6
    status_choices = (
        (SALE_NOT_STARTED, 'فروش آغاز نشده است'),
        (SALE_OPEN, 'در حال فروش بلیت'),
        (TICKETS_SOLD, 'بلیت ها تمام شد'),
        (SALE_CLOSED, 'فروش بلیت بسته شد'),
        (MOVIE_PLAYED, 'فیلم پخش شد'),
        (SHOW_CANCELED, 'سانس لغو شد'),
    )
    status = models.IntegerField(choices=status_choices, verbose_name='وضعیت')

    def __str__(self):
        return '{} - {} - {}'.format(self.movie, self.cinema, self.start_time)

    def get_price_display(self):
        return '{} تومان'.format(self.price)

    def reserve_seats(self, seat_count):
        """
        Reserves Seats for a customer
        :param seat_count: An Integer as the number of seats to be reserved
        :return:
        """
        assert isinstance(seat_count, int) and seat_count > 0, 'تعداد صندلی ها صحیح وارد نشده است'
        assert self.status == ShowTime.SALE_OPEN, 'فروش برای این سانس فعال نیست'
        assert self.free_seats >= seat_count, 'تعداد صندلی های خالی کافی نیست'
        self.free_seats -= seat_count
        if self.free_seats == 0:
            self.status = ShowTime.TICKETS_SOLD
        self.save()


class Ticket(models.Model):
    """
    Represents one or more tickets, bought by a user in an order
    """

    class Meta:
        verbose_name = 'بلیت'
        verbose_name_plural = 'بلیت'

    showtime = models.ForeignKey('ShowTime', on_delete=models.PROTECT, verbose_name='سانس')
    customer = models.ForeignKey('accounts.Profile', on_delete=models.PROTECT, verbose_name='خریدار')
    seat_counter = models.IntegerField(verbose_name='تعداد صندلی')
    order_time = models.DateTimeField(verbose_name='زمان خرید', auto_now_add=True)

    def __str__(self):
        return "{} بلیت به نام {} برای فیلم {}".format(self.seat_counter, self.customer, self.showtime.movie)

ticketing/forms.py
from django import forms

from ticketing.models import Cinema


class ShowTimeSearchForm(forms.Form):
    movie_name = forms.CharField(max_length=100, label='نام فیلم', required=False,
                                 widget=forms.TextInput(attrs={'class': 'something'}))
    sale_is_open = forms.BooleanField(label='فقط سانس های قابل فروش', required=False)
    movie_length_min = forms.IntegerField(label='حداقل زمان فیلم', min_value=0, max_value=200, required=False)
    movie_length_max = forms.IntegerField(label='حداکثر زمان فیلم', min_value=0, max_value=200, required=False)

    PRICE_ANY = '0'
    PRICE_UNDER_10 = '1'
    PRICE_10_TO_15 = '2'
    PRICE_15_TO_20 = '3'
    PRICE_ABOVE_20 = '4'
    PRICE_LEVEL_CHOICES = (
        (PRICE_ANY, 'هر قیمتی'),
        (PRICE_UNDER_10, 'تا 10 هزار تومان'),
        (PRICE_10_TO_15, '10 تا 15 هزار تومان'),
        (PRICE_15_TO_20, '15 تا 20 هزار تومان'),
        (PRICE_ABOVE_20, 'بیش از 20 هزار تومان'),
    )
    price_level = forms.ChoiceField(label='محدوده قیمت', choices=PRICE_LEVEL_CHOICES, required=False)

    cinema = forms.ModelChoiceField(label='سینما', queryset=Cinema.objects.all(), required=False)

    def get_price_boundaries(self):
        price_level = self.cleaned_data['price_level']
        if price_level == ShowTimeSearchForm.PRICE_UNDER_10:
            return None, 10000
        elif price_level == ShowTimeSearchForm.PRICE_10_TO_15:
            return 10000, 15000
        elif price_level == ShowTimeSearchForm.PRICE_15_TO_20:
            return 15000, 20000
        elif price_level == ShowTimeSearchForm.PRICE_ABOVE_20:
            return 20000, None
        else:
            return None, None

ticketing/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from accounts.models import Profile
from ticketing.forms import ShowTimeSearchForm
from ticketing.models import Movie, Cinema, ShowTime, Ticket


def movie_list(request):
    movies = Movie.objects.all()
    movie = Movie.objects.all().count()
    cinema = Cinema.objects.all().count()
    show = ShowTime.objects.filter(status=2).count()
    user = request.user.is_authenticated
    context = {
        'movie_list': movies,
        'movie': movie,
        'cinema': cinema,
        'show': show,
        'user': user,
    }

    return render(request, 'ticketing/movie_list.html', context)


def cinema_list(request):
    cinemas = Cinema.objects.all()
    movie = Movie.objects.all().count()
    cinema = Cinema.objects.all().count()
    show = ShowTime.objects.filter(status=2).count()
    user = request.user.is_authenticated
    context = {
        'cinema_list': cinemas,
        'movie': movie,
        'cinema': cinema,
        'show': show,
        'user': user,
    }

    return render(request, 'ticketing/cinema_list.html', context)


def movie_details(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    available_shows = ShowTime.objects.filter(movie=movie).order_by('status')
    user = request.user.is_authenticated
    context = {
        'movie': movie,
        'available_shows': available_shows,
        'user': user,
    }
    return render(request, 'ticketing/movie_details.html', context)


def cinema_details(request, cinema_id):
    cinema = get_object_or_404(Cinema, pk=cinema_id)
    available_shows = ShowTime.objects.filter(cinema=cinema).order_by('status')
    user = request.user.is_authenticated
    context = {
        'cinema': cinema,
        'available_shows': available_shows,
        'user': user,
    }
    return render(request, 'ticketing/cinema_details.html', context)


def showtime_list(request):
    # Search Form -----------------------------------------------
    search_form = ShowTimeSearchForm(request.GET)
    showtime = ShowTime.objects.all()
    if search_form.is_valid():
        showtime = showtime.filter(movie__name__contains=search_form.cleaned_data['movie_name'])
        if search_form.cleaned_data['sale_is_open']:
            showtime = showtime.filter(status=ShowTime.SALE_OPEN)
        if search_form.cleaned_data['movie_length_min'] is not None:
            showtime = showtime.filter(movie__length__gte=search_form.cleaned_data['movie_length_min'])
        if search_form.cleaned_data['movie_length_max'] is not None:
            showtime = showtime.filter(movie__length__lte=search_form.cleaned_data['movie_length_max'])
        if search_form.cleaned_data['cinema'] is not None:
            showtime = showtime.filter(cinema=search_form.cleaned_data['cinema'])

        min_price, max_price = search_form.get_price_boundaries()
        if min_price is not None:
            showtime = showtime.filter(price__gte=min_price)
        if max_price is not None:
            showtime = showtime.filter(price__lte=max_price)
    showtime = showtime.order_by('status')
    # End of Search Form -----------------------------------------------
    movie = Movie.objects.all().count()
    cinema = Cinema.objects.all().count()
    show = ShowTime.objects.filter(status=2).count()
    user = request.user.is_authenticated
    context = {
        'showtime': showtime,
        'movie': movie,
        'cinema': cinema,
        'show': show,
        'user': user,
        'search_form': search_form,
    }
    return render(request, 'ticketing/showtime_list.html', context)


@login_required
def showtime_details(request, showtime_id):
    showtime = ShowTime.objects.get(pk=showtime_id)
    profile = request.user.profile
    # Generate Options for DropDown Menu -----------------------------------------------
    salable_list = []
    salable = 10
    if showtime.free_seats < 10:
        salable = showtime.free_seats
    for i in range(1, salable + 1):
        salable_list.append(i)
    # End of Generate Options for DropDown Menu -----------------------------------------------
    context = {
        'showtime': showtime,
        'profile': profile,
        'salable_list': salable_list,
    }
    # Buying Tickets -----------------------------------------------
    if request.method == 'POST':
        try:
            seat_count = int(request.POST['seat_count'])
            assert showtime.status == ShowTime.SALE_OPEN, 'فروش برای این سانس غیرفعال است'
            assert showtime.free_seats >= seat_count, 'به اندازه کافی صندلی خالی وجود ندارد'
            total_price = showtime.price * seat_count
            assert request.user.profile.spend(total_price), 'موجودی  کافی نیست'
            showtime.reserve_seats(seat_count=seat_count)
            ticket = Ticket.objects.create(showtime=showtime, customer=request.user.profile, seat_counter=seat_count)
        except Exception as e:
            context['error'] = str(e)
        else:
            return HttpResponseRedirect(reverse('ticketing:ticket_details', kwargs={'ticket_id': ticket.id}))
    # End of Buying Tickets -----------------------------------------------
    return render(request, 'ticketing/showtime_details.html', context)


def home_page(request):
    movie = Movie.objects.all().count()
    cinema = Cinema.objects.all().count()
    show = ShowTime.objects.filter(status=2).count()
    user = request.user.is_authenticated
    context = {
        'movie': movie,
        'cinema': cinema,
        'show': show,
        'user': user,
    }
    return render(request, 'ticketing/index.html', context)


@login_required
def ticket_list(request):
    tickets = Ticket.objects.filter(customer=request.user.profile).order_by('-order_time')
    context = {
        'tickets': tickets,
    }
    return render(request, 'ticketing/ticket_list.html', context)


@login_required
def ticket_details(request, ticket_id):
    ticket = Ticket.objects.get(pk=ticket_id)
    context = {
        'ticket': ticket,
    }
    return render(request, 'ticketing/ticket_details.html', context)

ticketing/templates/ticketing/_ads.html
<div class="col-12 my-3 advertisment {{ class_name|default:'ads0' }}">
    تبلیغات
    {{ ads_name }}
    در این مکان
</div>

ticketing/templates/ticketing/base_page.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>
        {% block page_title %}{% endblock %}
    </title>
    <!-- BS & FA CSS only -->
    <script src="https://kit.fontawesome.com/124fb35ff9.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/main.css" %}">
</head>
<body>
<div class="container">
    <div class="row my-2 py-2">
        <h1>
            سامانه فروش بلیت سینما
        </h1>
    </div>

    {% block buttons %}
        <div class="row my-3">
            <div class="col"><a class="btn btn-primary btn-block" href="{% url 'home_page' %}" role="button">صفحه
                اصلی</a></div>
            <div class="col"><a class="btn btn-primary btn-block" href="{% url 'ticketing:movie_list' %}" role="button">لیست
                فیلم ها
                <span class="badge badge-light">{{ movie }}</span></a></div>
            <div class="col"><a class="btn btn-primary btn-block" href="{% url 'ticketing:cinema_list' %}"
                                role="button">لیست سینما ها
                <span class="badge badge-light">{{ cinema }}</span></a></div>
            <div class="col"><a class="btn btn-primary btn-block" href="{% url 'ticketing:showtime_list' %}"
                                role="button">لیست سانس ها
                <span class="badge badge-light">{{ show }}</span></a></div>
            {% if user %}
                <div class="col"><a class="btn btn-warning btn-block" href="{% url 'accounts:profile' %}" role="button">پنل
                    کاربری</a></div>
            {% else %}
                <div class="col"><a class="btn btn-warning btn-block" href="{% url 'accounts:login' %}" role="button">ورود</a>
                </div>
            {% endif %}
            <div class="col"><a class="btn btn-danger btn-block" href="{% url 'accounts:logout' %}"
                                role="button">خروج</a></div>
        </div>
    {% endblock %}
    <div class="row">
        {% block page_content %}{% endblock %}
    </div>
</div>
<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
<script src="{% static "ticketing/js/main.js" %}"></script>
</body>
</html>

ticketing/templates/ticketing/cinema_details.html
{% extends 'ticketing/base_page.html' %}

{% block page_title %}{{ cinema.name }}{% endblock %}

{% block page_content %}
    <table class="table table-hover table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">سینما:</th>
                <th scope="col">{{ cinema.name }}</th>
            </tr>
        </thead>
        <tr>
            <th scope="row">شهر:</th>
            <td>{{ cinema.city }}</td>
        </tr>
        <tr>
            <th scope="row">ظرفیت:</th>
            <td>{{ cinema.capacity }}</td>
        </tr>
        <tr>
            <th scope="row">تلفن:</th>
            <td>{{ cinema.phone_number }}</td>
        </tr>
        <tr>
            <th scope="row">آدرس:</th>
            <td>{{ cinema.address }}</td>
        </tr>
        {% if cinema.image %}
            <tr>
                <th scope="row">تصویر:</th>
                <td><img style="width: 250px" src="{{ cinema.image.url }}" alt="{{ cinema.name }}"></td>
            </tr>
        {% endif %}
        <tr>
            <th scope="row">سانس های موجود:</th>
            <td>
                <div class="row p-2">
                    {% for show in available_shows %}
                        <div class="col-4">
                            {% if show.status ==  2%}
                                <a href="{% url "ticketing:showtime_details" showtime_id=show.pk %}" class="btn btn-success p-4 m-2 btn-block">
                            {% else %}
                                <a href="{% url "ticketing:showtime_details" showtime_id=show.pk %}" class="btn btn-secondary p-4 m-2 btn-block disabled">
                            {% endif %}
                                <span>
                                    {{ show.movie }}
                                </span><br/>
                                <span class="badge badge-light">
                                    {{ show.cinema }}
                                </span><br/>
                                {% if show.status ==  2%}
                                    <span class="badge badge-pill badge-warning">
                                        {{ show.get_status_display }}
                                    </span><br/>
                                    <span>
                                        {{ show.get_price_display }}
                                    </span>
                                {% else %}
                                    <span class="badge badge-pill badge-danger">
                                        {{ show.get_status_display }}
                                    </span>
                                {% endif %}
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </td>
            </tr>
    </table>
{% endblock %}

ticketing/templates/ticketing/cinema_list.html
{% extends 'ticketing/base_page.html' %}

{% block page_title %}
    لیست سینما ها
{% endblock %}

{% block page_content %}
    {% if cinema_list %}
    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
                <th>
                    لیست سینما های فعال:
                </th>
            </tr>
        </thead>
        {% for cinema in cinema_list %}
            <tr>
                <td>
                    <a class="btn btn-outline-info btn-lg btn-block" href="{% url "ticketing:cinema_details" cinema_id=cinema.pk %}">{{ cinema }}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
        <p style="color: red">
        سینمایی موجود نیست
        </p>
    {% endif %}
{% endblock %}

ticketing/templates/ticketing/movie_details.html
{% extends "ticketing/base_page.html" %}

{% block page_title%}
    {{ movie.name }}
{% endblock %}

{% block buttons %}
    {{ block.super }}
    {% include "ticketing/_ads.html" with ads_name="divar" %}
{% endblock %}

{% block page_content %}
    <table class="table table-hover table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">فیلم:</th>
                <th scope="col">{{ movie.name }}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">کارگردان:</th>
                <td>{{ movie.director }}</td>
            </tr>
            <tr>
                <th scope="row">مدت فیلم:</th>
                <td>{{ movie.length }}</td>
            </tr>
            <tr>
                <th scope="row">سال انتشار:</th>
                <td>{{ movie.year }}</td>
            </tr>
            <tr>
                <th scope="row">داستان فیلم:</th>
                <td>{{ movie.description }}</td>
            </tr>
            <tr>
                <th scope="row">پوستر:</th>
                <td><img style="width: 250px" src="{{ movie.poster.url }}" alt="{{ movie.name }}"></td>
            </tr>
            <tr>
                <th scope="row">سانس های موجود:</th>
                <td>
                    <div class="row p-2">
                        {% for show in available_shows %}
                            <div class="col-4">
                                {% if show.status ==  2%}
                                    <a href="{% url "ticketing:showtime_details" showtime_id=show.pk %}" class="btn btn-success p-4 m-2 btn-block">
                                {% else %}
                                    <a href="{% url "ticketing:showtime_details" showtime_id=show.pk %}" class="btn btn-secondary p-4 m-2 btn-block disabled">
                                {% endif %}
                                    <span>
                                        {{ show.movie }}
                                    </span><br/>
                                    <span class="badge badge-light">
                                        {{ show.cinema }}
                                    </span><br/>
                                    {% if show.status ==  2%}
                                        <span class="badge badge-pill badge-warning">
                                            {{ show.get_status_display }}
                                        </span><br/>
                                        <span>
                                            {{ show.get_price_display }}
                                        </span>
                                    {% else %}
                                        <span class="badge badge-pill badge-danger">
                                            {{ show.get_status_display }}
                                        </span>
                                    {% endif %}
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    {% include "ticketing/_ads.html" with class_name='ads2' ads_name="samsung" %}
{% endblock %}

ticketing/templates/ticketing/showtime_details.html
{% extends "ticketing/base_page.html" %}

{% block page_title %}
    بلیت سانس
    {{ showtime.start_time |date:"y/n/j" }}
    برای فیلم
    {{ showtime.movie.name }}
{% endblock %}


{% block page_content %}
    <div class="col-2"></div>
    <div class="col-8 ">
        <div class="row my-5 p-4 bg-dark rounded">
            <div class="col-8 bg-light">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col" colspan="2" class="text-center">
                            خرید بلیت سانس
                            {{ showtime.start_time |date:"Y/n/j" }}
                            برای فیلم
                            {{ showtime.movie.name }}
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">
                            نام فیلم:
                        </th>
                        <td><a href="{% url "ticketing:movie_details" movie_id=showtime.movie_id %}">
                            {{ showtime.movie.name }}
                        </a></td>
                    </tr>
                    <tr>
                        <th scope="row">
                            نام سینما:
                        </th>
                        <td><a href="{% url "ticketing:cinema_details" cinema_id=showtime.cinema_id %}">
                            {{ showtime.cinema.name }}
                        </a></td>
                    </tr>
                    <tr>
                        <th scope="row">
                            نام و نام خانوادگی شما:
                        </th>
                        <td>
                            {{ profile.user.get_full_name }}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            ساعت شروع سانس:
                        </th>
                        <td>
                            {{ showtime.start_time|date:"H:i" }}
                        </td>
                    </tr>
                    {% if showtime.status == 2 %}
                        <tr class="alert alert-success">
                            {% else %}
                        <tr class="alert alert-danger">
                    {% endif %}
                    <th scope="row">
                        وضعیت سانس:
                    </th>
                    <td>
                        {{ showtime.get_status_display }}
                    </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            ظرفیت خالی:
                        </th>
                        <td>
                            {{ showtime.free_seats }}
                            صندلی
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            قیمت هر صندلی:
                        </th>
                        <td>
                            {{ showtime.price }}
                            تومان
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            موجودی کیف پول شما:
                        </th>
                        <td>
                            {{ profile.get_balance_display }}
                        </td>
                    </tr>
                    {% if showtime.status == 2 %}
                        <tr>
                            <th scope="row">
                                انتخاب تعداد بلیت:
                            </th>
                            <td>
                                <form action="" method="post" class="form-row">
                                    {% csrf_token %}
                                    <div class="col">
                                        <select name="seat_count" class="form-control">
                                            {% for sale in salable_list %}
                                                <option value="{{ sale }}">{{ sale }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn btn-success btn-block">
                                            خرید
                                        </button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    {% endif %}

                    {% if error %}
                        <tr class="bg-danger text-light">
                            <th scope="row">
                                خطا:
                            </th>
                            <td>
                                {{ error }}
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
            <div class="col-4 bg-light py-5">
                <img src="{{ showtime.movie.poster.url }}" class="card-img"
                     alt="{{ showtime.movie.name }}">
            </div>
        </div>
    </div>
    <div class="col-2"></div>
{% endblock %}

ticketing/templates/ticketing/showtime_list.html
{% extends 'ticketing/base_page.html' %}

{% block page_title %}
    سانس های نمایش
{% endblock %}

{% block page_content %}
    <div class="col-12 py-4">
        <form action="" method="get">
            <div class="form-group row">
                {{ search_form.as_p }}
                <button type="submit" class="btn btn-primary">جست و جو</button>
            </div>
        </form>
        {% if showtime %}
            <div class="alert alert-info">
                {{ showtime.count }}
                سانس یافت شد!
            </div>
        {% else %}
            <div class="alert alert-danger">
                سانسی با این مشخصات یافت نشد!
            </div>
        {% endif %}
    </div>
    {% for show in showtime %}
        <div class="col-3">
            {% if show.status ==  2 %}
                <a href="{% url "ticketing:showtime_details" showtime_id=show.pk %}"
                   class="btn btn-success p-4 m-2 btn-block">
            {% else %}
                <a href="{% url "ticketing:showtime_details" showtime_id=show.pk %}"
                   class="btn btn-secondary p-4 m-2 btn-block disabled">
            {% endif %}
            <span>
                    {{ show.movie }}
                </span><br/>
            <span class="badge badge-light">
                    {{ show.cinema }}
                </span><br/>
            <span class="badge badge-danger">
                    سانس
                    {{ show.start_time |date:"Y/n/j" }}
                </span><br/>
            {% if show.status ==  2 %}
                <span class="badge badge-pill badge-warning">
                        {{ show.get_status_display }}
                    </span><br/>
                <span>
                        {{ show.get_price_display }}
                    </span>
            {% else %}
                <span class="badge badge-pill badge-danger">
                        {{ show.get_status_display }}
                    </span>
            {% endif %}
            </a>
        </div>
    {% endfor %}


{% endblock %}